name: Automated Preprocessing

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:

      # Clone repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install Requirements
        run: |
          pip install pandas numpy scikit-learn kagglehub

      # Run preprocessing script
      - name: Run Automation Script
        run: |
          cd preprocessing
          python automate_Hana-fithri.py

      # Commit hasil preprocessing terbaru
      - name: Commit Preprocessed Dataset
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .

          git commit -m "Update preprocessing result" || echo "No changes to commit"

          git push
