# -*- coding: utf-8 -*-
"""Automate_Hana-Fithri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GE7AOHZ7iRO7V4j_Q7k6mCXBjIhzZnhB

# **1. Import Library**
"""

import pandas as pd
import numpy as np
import os

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

"""# **2. Load Data**"""

DATASET_PATH = "../simnangkis_eksport_mlati_raw/simnangkis_eksport_mlati.csv"

df = pd.read_csv(DATASET_PATH)

print("Dataset berhasil dimuat")
print("Shape awal:", df.shape)

"""# **3. Handle Missing Values**"""

num_cols = df.select_dtypes(include=np.number).columns

df.loc[:, num_cols] = df[num_cols].fillna(
    df[num_cols].median()
)

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df.loc[:, col] = df[col].fillna(
        df[col].mode()[0]
    )

"""# **4. Hapus Duplikat**"""

df.drop_duplicates(inplace=True)

print("Duplikat berhasil dihapus")

"""# **5. Feature Selection**"""

selected_features = [
    'id_pendidikan',
    'id_pekerjaan',
    'lantai',
    'dinding',
    'atap',
    'sumber_air_minum',
    'sumber_penerangan',
    'ada_motor',
    'ada_mobil',
    'ada_tv',
    'ada_lemari_es',
    'ada_emas'
]

df = df[selected_features].copy()

print("Feature selection selesai")

"""# **6. Feature Engineering**"""

df.loc[:, 'skor'] = (
    (df['ada_motor'] == 3).astype(int) +
    (df['ada_mobil'] == 3).astype(int) +
    (df['ada_tv'] == 3).astype(int) +
    (df['ada_lemari_es'] == 3).astype(int) +
    (df['ada_emas'] == 1).astype(int)
)

print("Feature engineering selesai")

"""# **7. Target Kategori**"""

def kategori_kesejahteraan(skor):
    if skor <= 2:
        return 'rendah'
    elif skor <= 4:
        return 'sedang'
    else:
        return 'tinggi'

df.loc[:, 'kesejahteraan'] = df['skor'].apply(
    kategori_kesejahteraan
)

print("Target kategori berhasil dibuat")

"""# **8. Endcoding**"""

def encode_data(dataframe):
    le = LabelEncoder()
    for col in dataframe.columns:
        if dataframe[col].dtype == 'object':
            dataframe.loc[:, col] = le.fit_transform(
                dataframe[col]
            )
    return dataframe

df = encode_data(df)

"""# **9. Feature Scaling**"""

def scaling(df):
    scaler = StandardScaler()
    feature_cols = df.drop(
        'kesejahteraan',
        axis=1
    ).columns
    df.loc[:, feature_cols] = scaler.fit_transform(
        df[feature_cols]
    )
    return df

df = scaling(df)

"""# **10. Split Data**"""

X = df.drop('kesejahteraan', axis=1)
y = df['kesejahteraan']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Split data selesai")

"""# **11. Save Output**"""

OUTPUT_DIR = "simnangkis_preprocessing"

os.makedirs(OUTPUT_DIR, exist_ok=True)

X_train.to_csv(
    os.path.join(OUTPUT_DIR, "X_train.csv"),
    index=False
)

X_test.to_csv(
    os.path.join(OUTPUT_DIR, "X_test.csv"),
    index=False
)

y_train.to_csv(
    os.path.join(OUTPUT_DIR, "y_train.csv"),
    index=False
)

y_test.to_csv(
    os.path.join(OUTPUT_DIR, "y_test.csv"),
    index=False
)

print("Dataset preprocessing berhasil disimpan")

